In [1]:
import numpy as np

In [17]:
X = np.array([1,0,1,0,0,0,
              0,1,0,0,0,0,
              1,1,0,0,0,0,
              1,0,0,1,1,0,
              0,0,0,1,0,1])

In [18]:
X = X.reshape(5,-1)

In [19]:
X[0].reshape(1,-1)

array([[1, 0, 1, 0, 0, 0]])

In [20]:
X[0].reshape(1,-1).T

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [28]:
Xi = X[[0]]

In [32]:
Xi.dot(Xi.T), Xi

(array([[2]]), array([[1, 0, 1, 0, 0, 0]]))

In [33]:
np.linalg.norm(Xi), np.linalg.norm(Xi.T)

(1.4142135623730951, 1.4142135623730951)

In [34]:
# X.dot(X.T)
# 5*6 => M,N => min(M,N) = K
X.T.dot(X) # 내적 (단어별)
np.linalg.norm(X, axis=1)

array([1.41421356, 1.        , 1.41421356, 1.73205081, 1.41421356])